### ISSUE TITLE
About sh distribution prior

### ISSUE THREAD

**Issue by LZleejean** [VCL3D/DeepPanoramaLighting#2]
The paper mentioned that thanks to the use of distributed priors, the performance of the network has been greatly improved.
But the code does not have an implementation of Equation.10. The last layer of the illumination model is a fully connected layer, and the Equation.1 is not used.
Can you introduce the specific usage of Equation.10? Which part of the code does it work? Thank you!

**Comment by VasilisGks** [comment]
Hi @LZleejean, the prior was only used during training. However, for your convenience you can find a code snippet below: 

```
magnitude = torch.norm(sh_coeffs, p=2, dim=1, keepdim=True)
sh_coeffs = torch.nn.functional.softmax(sh_coeffs, dim=1)
return magnitude * sh_coeffs
```
