### ISSUE TITLE
about the  resolution of  image

### ISSUE THREAD

**Issue by 85zhanghao** [VCL3D/DeepPanoramaLighting#3]
When  I change  the  size  of  image，I will get  the  error?   Does the size of the input image have to be resized to 512 × 256 ？
![1664109562985](https://user-images.githubusercontent.com/94844844/192143870-178b7e5b-81ac-4c19-92eb-e9b21389ab5a.png)

**Comment by VasilisGks** [comment]
Hi @85zhanghao , yes, the image should be resized to 512x256 before inference.
