### ISSUE TITLE
How can I get an HDRI image output?

### ISSUE THREAD

**Issue by ghost** [VCL3D/DeepPanoramaLighting#6]
If I run the code, I get this
![image](https://github.com/VCL3D/DeepPanoramaLighting/assets/33053458/ce075691-fe10-4d4a-88cc-09786d7ea7f3)

I need a HDRI image like this:
![image](https://github.com/VCL3D/DeepPanoramaLighting/assets/33053458/33ca43ac-0bcb-4d1d-94ef-94da415495f7)

Any help will be much appreciated...

**Comment by sunfanyunn** [comment]
same question here

**Comment by GEisfish** [comment]
same question tooooooo

**Comment by VasilisGks** [comment]
Hi @sunfanyunn , @GEisfish. You can use the output from `loaders/autoenc_ldr2hdr.py` . It should be noted that this model is trained using Neural illumination dataset (Song et al.)
